default_platform(:ios)

platform :ios do

  	desc "Take screenshots"
	lane :screenshots do
 	 capture_screenshots
 	 frame_screenshots(white: true)
 	 upload_to_app_store
	end

     desc "Incrementing Build Number"
      lane :increment_build do
           current_build_number = latest_testflight_build_number(version: "1.0")
           increment_build_number(
           build_number: current_build_number + 1
           )
      end

	desc "crete application"
	lane :create_app do
	  produce(app_identifier: 'com.personel.McFastDev2', app_name: 'McFastDev2')
	end

	desc "Build application"
	lane :build do
		xcversion(version: "12.0")
	        build_app
	end

	desc "Push a new beta build to TestFlight"
	lane :beta do
	      upload_to_testflight(ipa: "./fastlane/builds/McFastDev2.ipa")
	end

end